# Generated by Django 4.1 on 2022-10-30 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='age',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainers',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='image',
            field=models.ImageField(upload_to='trainers'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
