# Generated by Django 4.1 on 2022-10-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_trainers_age_alter_trainers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='image',
            field=models.ImageField(upload_to='trainers'),
        ),
    ]
