# Generated by Django 4.1 on 2022-10-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_trainers_age_alter_trainers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
