# Generated by Django 4.1 on 2022-11-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_lessons_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=150)),
                ('text2', models.CharField(max_length=150)),
                ('text3', models.CharField(max_length=150)),
                ('text4', models.CharField(max_length=150)),
            ],
        ),
    ]
