# Generated by Django 4.1 on 2022-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_hometexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslayt',
            name='file',
            field=models.ImageField(upload_to='homepage'),
        ),
    ]
