# Generated by Django 4.1.4 on 2023-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
